### ISSUE TITLE
The conf file definition is repetitive

### ISSUE THREAD

**Issue by kumy** [docker-leash/leash-server#26]
While writing documentation I found that the configuration file format is a bit repetitive. Right now if we want to have policy *allow docker run* and *allow docker run with name restriction* then it is written as 
```

openbar:
  containersCreate:
    Allow:
  containersWait:
    Allow:
  containersStart:
    Allow:
  containersAttach:
    Allow:

personnal:
  containersCreate:
    containerNameCheck:
      startwith:
        - foo
        - bar
  containersWait:
    containerNameCheck:
      startwith:
        - foo
        - bar
  containersStart:
    containerNameCheck:
      startwith:
        - foo
        - bar
  containersAttach:
    containerNameCheck:
      startwith:
        - foo
        - bar
```

What about those ideas?
* factorization directly using built-in yaml `references` feature support
* define a way to group keywords on one line:
```
openbar:
  containersCreate,containersWait,containersStart,containersAttach:
    Allow:

personnal:
  containersCreate,containersWait,containersStart,containersAttach:
    containerNameCheck:
      startwith:
        - foo
        - bar
```
* define a dedicated keyword in our syntax that will automatically expand
```
ie `containersRun` -> `containersCreate` + `containersWait` + `containersStart` + `containersAttach`)

openbar:
  containersRun:
    Allow:

personnal:
  containersRun:
    containerNameCheck:
      startwith:
        - foo
        - bar
```
