### ISSUE TITLE
Use case: restrict all users and allow all for admins

### ISSUE THREAD

**Issue by kumy** [docker-leash/leash-server#30]
In the documentation I wrote this conf example, however, I'm quite sure administrators wont have more access than other users...

### Restrict by container name
Here we want all users to have a limitation by the container name. All administrators are allowed to manage all containers.

`policies.yml`
```yml
---
containers_name_must_match_username:
  containers:
    containerNameCheck:
      startwith:
        - "$USER-"

readwrite:
  all:
    ReadWrite:
...
```

`groups.yml`
```yml
---
all:
  policies:
    - containers_name_must_match_username
  members:
    - "*"

administrators:
  policies:
    - readwrite
  members:
    - rda
    - mal
...
```
