### ISSUE TITLE
Add support for Hosts

### ISSUE THREAD

**Issue by kumy** [docker-leash/leash-server#33]
It would be nice to have the ability to define rules by host. We should be able to say "Allow group x to create containers"

example configuration:
`policies.xml`
```
  openbar:
    containersCreate:
      Allow:
```

`groups.xml`
```
  admins:
    policies:
      - openbar
  servers:
    - somehost.fqdn
    - someotherhost.fqdn
  members:
    - rda
    - mal
```

**Comment by kumy** [comment]
@romain-dartigues What about this file format:

```
---

## General file format:
# - description: <Optionnal: Human description of the ruleset>
#   hosts:
#     - <server name regexp>
#     - ...
#   default: <Default action if no rule match> (Deny, Allow, ReadOnly)
#   policies:
#     - members:
#         - <group name>
#         - ...
#       rules:
#         <action 1>:
#           <check>:
#         <action 2>:
#           <check>:
#             - <arg1>
#             - <arg2>
#             - ...
#         <action 3>:
#           <check>:
#             <arg1>: value
#             <arg1>: value
#             ...: ...
#
#     - ...:
#         - <group name>
#         - ...
#       rules:
#         ...:

## Rules are matched as:
## * find first ruleset the match hostname
## * find first policy the current user is in
## * apply rules (without specific order)
## ** if no rule match, fallback to default.


- description: Servers are fully accessible to Admins
               Monitoring group can only list containers.
               Default policy is Deny.
  hosts:
    - ^srv\d\d.*
  default: Deny
  policies:
    - members:
        - admins
      rules:
        any:
          Allow:

    - members:
        - monitoring
      rules:
        containersList:
          Allow:


- description: Users have access to containers and images starting by their name.
               Admin have full access to the host.
               Default policy is ReadOnly.
  hosts:
    - ^wks\d\d.*
  default: ReadOnly
  policies:
    - members:
        - admins
      rules:
        any:
          Allow:

    - members:
        - users
      rules:
        containersLogs:
          ContainerName:
            - ^bar-
            - ^foo-
            - ^$USER-
        containers:
          ContainerName:
            - ^foo-
            - ^$USER-
          ImagesName:
            - ^foo-
            - ^$USER-
          BindVolumes:
            - -/
            - +/home/$USER
            - +/0
        images:
          ImagesName:
            - ^foo-
            - ^$USER-


- description: For all other hosts,
               Admin have full access to the host.
               Deny access to Anonymous users.
               Default policy is ReadOnly.
  hosts:
    - .*
  default: ReadOnly
  policies:
    - members:
        - admins
      rules:
        any:
          Allow:
    - members:
        - Anonymous
      rules:
        any:
          Deny:

...
```

**Comment by romain-dartigues** [comment]
Looks good.

Shall the `hosts` syntax be the same as the volumes (about the +/- prefix)? What about the ImageName and other regex rules?

**Comment by kumy** [comment]
Nice idea for the `hosts` part. I'll add some tests to support it. (And adapt the example bellow)

`ImageName` or other checks are free to support any argument they need. ie: it's not important for the config rule parser. they are passed as is.

**Comment by kumy** [comment]
@romain-dartigues is this what you were thinking about?
```
- description: Servers are fully accessible to Admins
               Monitoring group can only list containers.
               Default policy is Deny.
  hosts:
    - +^srv\d\d.*
    - -^srv3\d.*
    - +^srv38.*
  default: Deny
```
