### ISSUE TITLE
`action_mapper` has incomplete regex

### ISSUE THREAD

**Issue by kumy** [docker-leash/leash-server#55]
While deploying on Geokrety project, I had those requests:

```
leashserver_1  | PAYLOAD AUTHENTICATED USER=u'geokrety' URI=u'/v1.22/images/geokretymap/gkm-website/json' METHOD=u'GET'

leashserver_1  | PAYLOAD AUTHENTICATED USER=u'geokrety' URI=u'/v1.22/images/geokretymap/gkm-api-cron:master/json' METHOD=u'GET'
```

Our regex are incomplete at https://github.com/docker-leash/leash-server/blob/master/docker_leash/action_mapper.py#L38 as the name part is not always an UUID as I expected, but also a full tag.

Related `docker-compose.yml`:

```
  gkm-website:
    build: /srv/GIT/geokretymap.github.io/
    image: geokretymap/gkm-website
    container_name: gkm-website

  gkm-api-cron:
    build: /srv/GIT/geokretymap-cron/master
    container_name: gkm-api-cron
    image: geokretymap/gkm-api-cron:master
    [...]
```
