### ISSUE TITLE
`containerName` and `readOnly` result in "container name not found"

### ISSUE THREAD

**Issue by kumy** [docker-leash/leash-server#56]
With such configuration, it is not possible to issue `docker ps`

policies.yml
```
---                       
                          
openbar:                  
  any:                    
    Allow:                
                          
geokrety:                 
  containers:             
    ContainerName: "^gk-" 
    ContainerName: "^gkm-"
                          
restricted:               
  containers:             
    BindVolumes:          
      - "-/"              
      - "+/home/$USER"    
                          
readonly:                 
  any:                    
    Allow:
```

groups.yml
```
admins:
  policies:
    - openbar
  members:
    - kumy
    - root-tr1
                 
geokrety:        
  policies:      
    - restricted
    - geokrety   
  members:       
    - geokrety   
                 
all:             
  policies:      
    - readonly   
  members:       
    - "*"
```

```
leashserver_1  | [2018-01-20 21:08:46 +0000] [8] [DEBUG] POST /AuthZPlugin.AuthZReq
leashserver_1  | --------------------------------------------------------------------------------
leashserver_1  | INFO in payload [/srv/docker-leash/docker_leash/payload.py:55]:
leashserver_1  | PAYLOAD AUTHENTICATED USER=u'geokrety' URI=u'/v1.35/containers/json' METHOD=u'GET'
leashserver_1  | --------------------------------------------------------------------------------
leashserver_1  | --------------------------------------------------------------------------------
leashserver_1  | ERROR in leash_server [/srv/docker-leash/docker_leash/leash_server.py:146]:
leashserver_1  | REQUEST DENIED: Container name verification failed: container name not found
leashserver_1  | --------------------------------------------------------------------------------

```
